### ISSUE TITLE
About the config file on MS-COCO

### ISSUE THREAD

**Issue by zye-shen** [MCG-NJU/DGN#2]
Thank you for your contribution.Did you train on the COCO dataset? Can you share the config files about the training and testing configuration on COCO ? Looking forward to your reply

**Comment by ArchNew** [comment]
It does involve some tricks. My work is largely inspired by OPEC-Net, so I used that project as a starting point, including the datasets it utilizes. OPEC-Net trains its model on a combined dataset from COCO and CrowdPose, and reports results as the CrowdPose dataset's.

If you want to train the model on COCO only, there’s a useful trick you can try. OPEC-Net provides a version of the training dataset picked from COCO, and you can create your own version of this dataset using ground truth bounding boxes or those generated by an off-the-shelf detector (which should differ from the one used in OPEC-Net). This way, you’ll have two versions of the dataset, both sourced from COCO but with different variations. You can then train your model on these combined datasets.

If you prefer datasets with 17 keypoints instead of the 12 used in OPEC-Net, you can generate both versions of COCO yourself. One version can be based on the detected bounding boxes (which you could extract from the COCO version provided by OPEC-Net), and the other can be based on the ground truth bounding boxes (or alternatively, you can generate bounding boxes using an off-the-shelf object detector).

**Comment by Zhiye-Shen** [comment]
已收到

**Comment by zye-shen** [comment]
Thanks for your reply.
“OPEC-Net provides a version of the training dataset picked from COCO, and you can create your own version of this dataset using ground truth bounding boxes or those generated by an off-the-shelf detector (which should differ from the one used in OPEC-Net).”
Where can I find this version.

**Comment by ArchNew** [comment]
At OPEC-Net project page on github. It seems there is some misunderstanding about how OPEC-Net and my DGN were trained on the CrowdPose dataset. We trained on both the COCO and CrowdPose datasets, and the inference results were generated by an off-the-shelf pose estimation network.

Strictly speaking, both my work and OPEC-Net focus on pose fine-tuning, not traditional pose estimation. We take the pose estimation results from an off-the-shelf network and fine-tune them using our own models. Hence, you can fine pre-finetune results on both COCO and CrowdPose on OPEC-Net project's official GitHub page.

One more thing: nowadays, there are better ways to learn the relationships among joints while extracting appearance features. My work, as well as OPEC-Net, separates appearance feature extraction and joint relationship learning into two stages, which is not an ideal solution. A more effective approach would be to extract features and learn joint relationships simultaneously, or in a single forward pass. This forces the model to learn both key elements—appearance features and joint relationships—in a more cohesive and integrated way. Additionally, such models are easier to train and tune.
